version: '3'

services:
  db:
    restart: always
  web:
    command: gunicorn -b 0.0.0.0:80 giftshop.wsgi
    env_file: .env.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db